analyzer:
  strong-mode: true
  exclude:
    - "**/*.dart_tool/*"
    - "**/build/*"
  errors:
    uri_does_not_exist: ignore
linter:
  rules:
    # Errors
    - avoid_empty_else
    - control_flow_in_finally
    - empty_statements
    - test_types_in_equals
    - throw_in_finally
    - valid_regexps

    # Style
    - annotate_overrides
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - await_only_futures
    - camel_case_types
    - comment_references
    - empty_catches
    - empty_constructor_bodies
    - hash_and_equals
    - library_prefixes
    - non_constant_identifier_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - type_init_formals
    - unrelated_type_equality_checks
